### ISSUE TITLE
1주차 자바스크립트 발표자료

### ISSUE THREAD

**Issue by Seongil-Shin** [EndlessCreation/Node-study-2021-1#1]

**Comment by Seongil-Shin** [comment]
[정규식 pdf](https://drive.google.com/file/d/1cxpZE40EBdfWu4SMRk_q2abLHWCG83VF/view?usp=sharing, "go pdf")

**Comment by ExcludedPluto** [comment]
> [정규식 pdf](https://drive.google.com/file/d/1cxpZE40EBdfWu4SMRk_q2abLHWCG83VF/view?usp=sharing,)

**Comment by InHyeok-J** [comment]
https://www.notion.so/callback-f430e58deeac4c50a04deef4fd064bf3

**Comment by ritty27** [comment]
[js정리중](https://www.notion.so/JavaScript-0d0cb7433fa44a11b5b6a0032c9d61be)

**Comment by akrudal** [comment]
https://www.notion.so/JAVASCRIPT-API-b944eb7c183d4ce2a828cf3e4d93c50b

**Comment by yexjin** [comment]
[https://www.notion.so/JSON-7f3be0fc9bcd44b9b85f030f18d25899](url)

**Comment by yexjin** [comment]
[https://www.notion.so/JSON-7f3be0fc9bcd44b9b85f030f18d25899](url)

**Comment by EomYoosang** [comment]
https://dbtkd1801.gitbook.io/yeeeee/nodejs/javascript_prototype

**Comment by yexjin** [comment]
https://www.notion.so/JSON-7f3be0fc9bcd44b9b85f030f18d25899

**Comment by yexjin** [comment]
[https://www.notion.so/JSON-7f3be0fc9bcd44b9b85f030f18d25899](url)

**Comment by yexjin** [comment]
[https://www.notion.so/JSON-7f3be0fc9bcd44b9b85f030f18d25899](url)

**Comment by yexjin** [comment]
https://www.notion.so/JSON-7f3be0fc9bcd44b9b85f030f18d25899
