### ISSUE TITLE
2주차 자바스크립트 발표자료

### ISSUE THREAD

**Issue by Seongil-Shin** [EndlessCreation/Node-study-2021-1#2]

**Comment by Seongil-Shin** [comment]
데코레이터 패턴 https://www.notion.so/2d5ef0f8ab6441efa785eb9144f26c76

**Comment by akrudal** [comment]
Async와 Await https://www.notion.so/JAVASCRIPT-Async-Await-ca74e6cd82c8498c8b9b53eb8251a059

**Comment by yexjin** [comment]
함수 객체의 프로퍼티, 기명 함수 표현식[https://www.notion.so/0399e4b659914b2d9e0061a6a067c7c7](https://www.notion.so/0399e4b659914b2d9e0061a6a067c7c7)

**Comment by InHyeok-J** [comment]
https://www.notion.so/Promise-async-await-7a636c64b1364f8481fa72575baba642  
Promise, async await

**Comment by EomYoosang** [comment]
https://dbtkd1801.gitbook.io/yeeeee/node.js/javascript_prototype

**Comment by ritty27** [comment]
[프로퍼티](https://www.notion.so/JavaScript2-c171cd04d7954860ad6604755862232b)
