### ISSUE TITLE
4주차) 노드 스터디 정리링크

### ISSUE THREAD

**Issue by Seongil-Shin** [EndlessCreation/Node-study-2021-1#4]

**Comment by EomYoosang** [comment]
https://dbtkd1801.gitbook.io/yeeeee/nodejs_head/nodejs3

3~5가 4주차 내용입니다

**Comment by akrudal** [comment]
https://www.notion.so/Node-js-4-9abb9dfef4ac4bf2bde964f7766ebe5b
아직 정리 다 못했는데, 까먹을 것 같아서 미리 올립니다!

**Comment by ritty27** [comment]
[3장](https://www.notion.so/3-d5bae3c4b4f64dac91e3aa73fb33f01d)

**Comment by yexjin** [comment]
[https://www.notion.so/a3d267df0e014fe48b7d6b289c7cb433](https://www.notion.so/a3d267df0e014fe48b7d6b289c7cb433) 
 정리 토요일 새벽내로 더 추가해서
 마무리 할 예정입니다 ㅠㅠ

**Comment by InHyeok-J** [comment]
https://www.notion.so/4-011831067ffc4245bbad6594a4a6ec62

**Comment by Seongil-Shin** [comment]
https://seongil-shin.github.io/posts/node_ch3/
https://seongil-shin.github.io/posts/node_ch5/
