### ISSUE TITLE
6주차) 노드 스터디 정리 링크

### ISSUE THREAD

**Issue by Seongil-Shin** [EndlessCreation/Node-study-2021-1#6]
7장 정리 링크 올려주시면 됩니다~

**Comment by Seongil-Shin** [comment]
https://seongil-shin.github.io/posts/node_ch7/

**Comment by yexjin** [comment]
[7장 MySQL](https://www.notion.so/7-MySQL-085dc70301a24fc4b4d9696ee301a3e3)

**Comment by InHyeok-J** [comment]
https://www.notion.so/6-4ed3baa5b37b4d2782560f6f2f97c257

**Comment by akrudal** [comment]
https://www.notion.so/Node-js-6-2ecb64ea403b47f0b62665e74c58bc91

**Comment by ritty27** [comment]
[7장 늦어서 죄송합니다](https://www.notion.so/7-a7d9537d306742e7869fcbab6c991a0b)
